CREATE TABLE IF NOT EXISTS "vde_user_mapping" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vde_user_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"auth_user_id" text NOT NULL,
	"mapping_user_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "vde_user_mapping_auth_user_id_unique" UNIQUE("auth_user_id"),
	CONSTRAINT "vde_user_mapping_mapping_user_id_unique" UNIQUE("mapping_user_id")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vde_user_mapping" ADD CONSTRAINT "vde_user_mapping_auth_user_id_users_id_fk" FOREIGN KEY ("auth_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_mapping_auth_user_id_idx" ON "vde_user_mapping" USING btree ("auth_user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_mapping_mapping_user_id_idx" ON "vde_user_mapping" USING btree ("mapping_user_id");